# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "funeral"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset:   "UTF-8"

# template engine
# simple: default and very basic template engine
#template_toolkit: TT

#template: template_toolkit
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

plugins:
    Database:
        driver: 'Pg'
        database: 'postgres'
        username: 'postgres'
        password: '7025'
        host: 'localhost'

ssh:
  client: 
     1: '10.70.116.41'
     2: '10.70.116.42'
     3: '10.70.116.43'
     5: '10.70.116.45'
     6: '10.70.116.46'
     7: '10.70.116.47'
     8: '10.70.116.48'
     9: '10.70.116.49'
     10: '10.70.116.50'
     11: '10.70.116.51'
  userid: 'pi'
  passwd: 'svhf8460'

url:
  host: 'http://10.70.116.40:5000'
